"""ops npt events

Revision ID: 30f34f52b9f4
Revises: 6c1740fe9d87
Create Date: 2026-07-24 00:15:49.417773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30f34f52b9f4'
down_revision: Union[str, None] = '6c1740fe9d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_npt_events',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('time_summary_row_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('npt_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cause', sa.String(length=300), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('gross_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('net_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('failure_md', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('contractual_link', sa.String(length=50), nullable=True),
    sa.Column('contractual_no', sa.String(length=50), nullable=True),
    sa.Column('type_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('equip_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('preventive_actions', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ops_npt_events.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['ops_npt_events.id'], ),
    sa.ForeignKeyConstraint(['time_summary_row_id'], ['ops_time_summary_rows.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_npt_events_daily_report_id'), 'ops_npt_events', ['daily_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_npt_events_daily_report_id'), table_name='ops_npt_events')
    op.drop_table('ops_npt_events')
    # ### end Alembic commands ###
