"""ops well and wellbore extended fields

Revision ID: 66ad1204ad96
Revises: 8fca0566a70a
Create Date: 2026-07-23 22:59:03.866617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ad1204ad96'
down_revision: Union[str, None] = '8fca0566a70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_well_plans',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('afe_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_well_plans_event_id'), 'ops_well_plans', ['event_id'], unique=True)
    op.add_column('ops_wellbores', sa.Column('api12', sa.String(length=20), nullable=True))
    op.add_column('ops_wellbores', sa.Column('arch_no', sa.String(length=50), nullable=True))
    op.add_column('ops_wellbores', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('ops_wellbores', sa.Column('drilling_end_date', sa.Date(), nullable=True))
    op.add_column('ops_wellbores', sa.Column('completion_end_date', sa.Date(), nullable=True))
    op.add_column('ops_wellbores', sa.Column('vs_azimuth', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ops_wellbores', sa.Column('max_angle_est', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ops_wellbores', sa.Column('kick_off_top_md', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ops_wellbores', sa.Column('kick_off_top_tvd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ops_wells', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('ops_wells', sa.Column('well_classification', sa.String(length=100), nullable=True))
    op.add_column('ops_wells', sa.Column('datum_name', sa.String(length=50), nullable=True))
    op.add_column('ops_wells', sa.Column('datum_elevation', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ops_wells', sa.Column('ground_elevation', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ops_wells', 'ground_elevation')
    op.drop_column('ops_wells', 'datum_elevation')
    op.drop_column('ops_wells', 'datum_name')
    op.drop_column('ops_wells', 'well_classification')
    op.drop_column('ops_wells', 'country')
    op.drop_column('ops_wellbores', 'kick_off_top_tvd')
    op.drop_column('ops_wellbores', 'kick_off_top_md')
    op.drop_column('ops_wellbores', 'max_angle_est')
    op.drop_column('ops_wellbores', 'vs_azimuth')
    op.drop_column('ops_wellbores', 'completion_end_date')
    op.drop_column('ops_wellbores', 'drilling_end_date')
    op.drop_column('ops_wellbores', 'start_date')
    op.drop_column('ops_wellbores', 'arch_no')
    op.drop_column('ops_wellbores', 'api12')
    op.drop_index(op.f('ix_ops_well_plans_event_id'), table_name='ops_well_plans')
    op.drop_table('ops_well_plans')
    # ### end Alembic commands ###
