"""ops daily report and time summary

Revision ID: 6c1740fe9d87
Revises: e6bcd407a81a
Create Date: 2026-07-23 23:59:14.281797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c1740fe9d87'
down_revision: Union[str, None] = 'e6bcd407a81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_step_catalog',
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_step_catalog_profile'), 'ops_step_catalog', ['profile'], unique=False)
    op.create_table('ops_daily_reports',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_no', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('supervisor', sa.String(length=200), nullable=True),
    sa.Column('engineer', sa.String(length=200), nullable=True),
    sa.Column('geologist', sa.String(length=200), nullable=True),
    sa.Column('dol', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('dfs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_md', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('md', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tvd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('progress', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rotating_hrs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sliding_hrs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hole_size', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('formation', sa.String(length=200), nullable=True),
    sa.Column('lithology', sa.String(length=200), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('summary_24hr', sa.Text(), nullable=True),
    sa.Column('forecast_24hr', sa.Text(), nullable=True),
    sa.Column('general_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'report_date', name='uq_daily_report_event_date')
    )
    op.create_index(op.f('ix_ops_daily_reports_event_id'), 'ops_daily_reports', ['event_id'], unique=False)
    op.create_table('ops_time_summary_rows',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('time_from', sa.String(length=5), nullable=True),
    sa.Column('time_to', sa.String(length=5), nullable=True),
    sa.Column('step_no', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('op_class', sa.String(length=10), nullable=True),
    sa.Column('op_code', sa.String(length=50), nullable=True),
    sa.Column('operation_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_time_summary_rows_daily_report_id'), 'ops_time_summary_rows', ['daily_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_time_summary_rows_daily_report_id'), table_name='ops_time_summary_rows')
    op.drop_table('ops_time_summary_rows')
    op.drop_index(op.f('ix_ops_daily_reports_event_id'), table_name='ops_daily_reports')
    op.drop_table('ops_daily_reports')
    op.drop_index(op.f('ix_ops_step_catalog_profile'), table_name='ops_step_catalog')
    op.drop_table('ops_step_catalog')
    # ### end Alembic commands ###
