"""engineering designs

Revision ID: 77ce554bed28
Revises: 9ba91ebd3859
Create Date: 2026-07-24 14:54:51.158597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77ce554bed28'
down_revision: Union[str, None] = '9ba91ebd3859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_engineering_designs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'module', name='uq_eng_design_event_module')
    )
    op.create_index(op.f('ix_ops_engineering_designs_event_id'), 'ops_engineering_designs', ['event_id'], unique=False)
    op.create_index(op.f('ix_ops_engineering_designs_module'), 'ops_engineering_designs', ['module'], unique=False)
    # Legacy processed_datasets/processed_records/wells churn pruned as usual.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned)
    op.drop_index(op.f('ix_ops_engineering_designs_module'), table_name='ops_engineering_designs')
    op.drop_index(op.f('ix_ops_engineering_designs_event_id'), table_name='ops_engineering_designs')
    op.drop_table('ops_engineering_designs')
    # ### end Alembic commands ###
