"""ops capture subsections

Revision ID: 844b9654b584
Revises: 30f34f52b9f4
Create Date: 2026-07-24 00:49:35.439883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '844b9654b584'
down_revision: Union[str, None] = '30f34f52b9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_bha_components',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=60), nullable=True),
    sa.Column('od_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('id_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('length_ft', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('serial_no', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_bha_components_daily_report_id'), 'ops_bha_components', ['daily_report_id'], unique=False)
    op.create_table('ops_casing_components',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=60), nullable=True),
    sa.Column('od_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('id_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('weight_ppf', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('grade', sa.String(length=300), nullable=True),
    sa.Column('connection', sa.String(length=300), nullable=True),
    sa.Column('top_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bottom_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('length_ft', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_casing_components_daily_report_id'), 'ops_casing_components', ['daily_report_id'], unique=False)
    op.create_table('ops_cement_jobs',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('casing_size', sa.String(length=300), nullable=True),
    sa.Column('slurry_type', sa.String(length=300), nullable=True),
    sa.Column('cement_class', sa.String(length=60), nullable=True),
    sa.Column('density_ppg', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('volume_bbl', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('top_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bottom_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('returns_pct', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_cement_jobs_daily_report_id'), 'ops_cement_jobs', ['daily_report_id'], unique=False)
    op.create_table('ops_cost_items',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('vendor', sa.String(length=300), nullable=True),
    sa.Column('afe_code', sa.String(length=300), nullable=True),
    sa.Column('qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_cost_items_daily_report_id'), 'ops_cost_items', ['daily_report_id'], unique=False)
    op.create_table('ops_fluid_readings',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('mud_type', sa.String(length=300), nullable=True),
    sa.Column('weight_ppg', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('funnel_vis', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('pv', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('yp', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('ph', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('chlorides', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_fluid_readings_daily_report_id'), 'ops_fluid_readings', ['daily_report_id'], unique=False)
    op.create_table('ops_personnel_entries',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('position', sa.String(length=300), nullable=True),
    sa.Column('persons', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_personnel_entries_daily_report_id'), 'ops_personnel_entries', ['daily_report_id'], unique=False)
    op.create_table('ops_pipe_tally_joints',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('joint_no', sa.Integer(), nullable=True),
    sa.Column('length_ft', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('cumulative_ft', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('od_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('serial_no', sa.String(length=300), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_pipe_tally_joints_daily_report_id'), 'ops_pipe_tally_joints', ['daily_report_id'], unique=False)
    op.create_table('ops_remarks',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_remarks_daily_report_id'), 'ops_remarks', ['daily_report_id'], unique=False)
    op.create_table('ops_safety_events',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=True),
    sa.Column('severity', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_safety_events_daily_report_id'), 'ops_safety_events', ['daily_report_id'], unique=False)
    op.create_table('ops_survey_stations',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('inclination', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('azimuth', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('tvd', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('ns', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('ew', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('dls', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_survey_stations_daily_report_id'), 'ops_survey_stations', ['daily_report_id'], unique=False)
    # NOTE: autogenerate also emitted a wave of alter_column/index/FK churn on
    # the legacy processed_datasets/processed_records/wells tables (runtime-
    # reflected, not ORM-owned) — pruned by hand, same as every prior ops
    # migration. This revision only creates the 10 new ops_* capture tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_survey_stations_daily_report_id'), table_name='ops_survey_stations')
    op.drop_table('ops_survey_stations')
    op.drop_index(op.f('ix_ops_safety_events_daily_report_id'), table_name='ops_safety_events')
    op.drop_table('ops_safety_events')
    op.drop_index(op.f('ix_ops_remarks_daily_report_id'), table_name='ops_remarks')
    op.drop_table('ops_remarks')
    op.drop_index(op.f('ix_ops_pipe_tally_joints_daily_report_id'), table_name='ops_pipe_tally_joints')
    op.drop_table('ops_pipe_tally_joints')
    op.drop_index(op.f('ix_ops_personnel_entries_daily_report_id'), table_name='ops_personnel_entries')
    op.drop_table('ops_personnel_entries')
    op.drop_index(op.f('ix_ops_fluid_readings_daily_report_id'), table_name='ops_fluid_readings')
    op.drop_table('ops_fluid_readings')
    op.drop_index(op.f('ix_ops_cost_items_daily_report_id'), table_name='ops_cost_items')
    op.drop_table('ops_cost_items')
    op.drop_index(op.f('ix_ops_cement_jobs_daily_report_id'), table_name='ops_cement_jobs')
    op.drop_table('ops_cement_jobs')
    op.drop_index(op.f('ix_ops_casing_components_daily_report_id'), table_name='ops_casing_components')
    op.drop_table('ops_casing_components')
    op.drop_index(op.f('ix_ops_bha_components_daily_report_id'), table_name='ops_bha_components')
    op.drop_table('ops_bha_components')
    # ### end Alembic commands ###
