"""approval workflow validation rules attachments

Revision ID: 9ba91ebd3859
Revises: a42a33b975a5
Create Date: 2026-07-24 03:03:36.848013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ba91ebd3859'
down_revision: Union[str, None] = 'a42a33b975a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_attachments',
    sa.Column('owner_type', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_attachments_owner_id'), 'ops_attachments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ops_attachments_owner_type'), 'ops_attachments', ['owner_type'], unique=False)
    op.create_table('ops_validation_rules',
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('check', sa.String(length=40), nullable=False),
    sa.Column('param1', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('param2', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('field_name2', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_validation_rules_report_type'), 'ops_validation_rules', ['report_type'], unique=False)
    # NOT NULL columns get a server_default so the ALTER succeeds against the
    # existing daily_report rows (dropped from the model, kept only in the DB).
    op.add_column('ops_daily_reports', sa.Column('workflow_status', sa.String(length=20), nullable=False, server_default='Draft'))
    op.add_column('ops_daily_reports', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('ops_daily_reports', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('ops_daily_reports', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.add_column('ops_daily_reports', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('ops_daily_reports', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_ops_daily_reports_approved_by', 'ops_daily_reports', 'users', ['approved_by'], ['id'])
    op.create_foreign_key('fk_ops_daily_reports_submitted_by', 'ops_daily_reports', 'users', ['submitted_by'], ['id'])
    # Legacy processed_datasets/processed_records/wells churn pruned as usual.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned)
    op.drop_constraint('fk_ops_daily_reports_submitted_by', 'ops_daily_reports', type_='foreignkey')
    op.drop_constraint('fk_ops_daily_reports_approved_by', 'ops_daily_reports', type_='foreignkey')
    op.drop_column('ops_daily_reports', 'approved_by')
    op.drop_column('ops_daily_reports', 'approved_at')
    op.drop_column('ops_daily_reports', 'submitted_by')
    op.drop_column('ops_daily_reports', 'submitted_at')
    op.drop_column('ops_daily_reports', 'is_locked')
    op.drop_column('ops_daily_reports', 'workflow_status')
    op.drop_index(op.f('ix_ops_validation_rules_report_type'), table_name='ops_validation_rules')
    op.drop_table('ops_validation_rules')
    op.drop_index(op.f('ix_ops_attachments_owner_type'), table_name='ops_attachments')
    op.drop_index(op.f('ix_ops_attachments_owner_id'), table_name='ops_attachments')
    op.drop_table('ops_attachments')
    # ### end Alembic commands ###
