"""wellhead and pump operations subsections

Revision ID: a42a33b975a5
Revises: d783dba8712a
Create Date: 2026-07-24 02:02:57.635439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a42a33b975a5'
down_revision: Union[str, None] = 'd783dba8712a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_pump_operations',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=300), nullable=True),
    sa.Column('liner_size_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('spm', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('pressure_psi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('flow_rate_gpm', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('hours_run', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_pump_operations_daily_report_id'), 'ops_pump_operations', ['daily_report_id'], unique=False)
    op.create_table('ops_wellhead_components',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=300), nullable=True),
    sa.Column('pressure_rating', sa.String(length=300), nullable=True),
    sa.Column('manufacturer', sa.String(length=300), nullable=True),
    sa.Column('serial_no', sa.String(length=300), nullable=True),
    sa.Column('associated_string', sa.String(length=60), nullable=True),
    sa.Column('test_pressure_psi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_wellhead_components_daily_report_id'), 'ops_wellhead_components', ['daily_report_id'], unique=False)
    # Legacy processed_datasets/processed_records/wells churn pruned (runtime-
    # reflected tables, not ORM-owned) — same as every prior ops migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_wellhead_components_daily_report_id'), table_name='ops_wellhead_components')
    op.drop_table('ops_wellhead_components')
    op.drop_index(op.f('ix_ops_pump_operations_daily_report_id'), table_name='ops_pump_operations')
    op.drop_table('ops_pump_operations')
    # ### end Alembic commands ###
