"""drilling parameters grid

Revision ID: ca9ec42c1474
Revises: f3dc2669d180
Create Date: 2026-07-24 19:06:54.468588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca9ec42c1474'
down_revision: Union[str, None] = 'f3dc2669d180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_drill_params',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('depth_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('formation', sa.String(length=300), nullable=True),
    sa.Column('bit_size', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('wob', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('rpm', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('flow_gpm', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('torque_ftlb', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('spp_psi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('rop', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('mse_ksi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_drill_params_daily_report_id'), 'ops_drill_params', ['daily_report_id'], unique=False)
    # Legacy processed_datasets/processed_records/wells churn pruned as usual.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned)
    op.drop_index(op.f('ix_ops_drill_params_daily_report_id'), table_name='ops_drill_params')
    op.drop_table('ops_drill_params')
    # ### end Alembic commands ###
