"""planning program subsections and wellplan expansion

Revision ID: d783dba8712a
Revises: 844b9654b584
Create Date: 2026-07-24 01:19:46.939450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd783dba8712a'
down_revision: Union[str, None] = '844b9654b584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_plan_casing',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=60), nullable=True),
    sa.Column('od_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('weight_ppf', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('grade', sa.String(length=300), nullable=True),
    sa.Column('connection', sa.String(length=300), nullable=True),
    sa.Column('setting_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('setting_tvd', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_casing_event_id'), 'ops_plan_casing', ['event_id'], unique=False)
    op.create_table('ops_plan_cement',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=60), nullable=True),
    sa.Column('slurry_type', sa.String(length=300), nullable=True),
    sa.Column('density_ppg', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('volume_bbl', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('top_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bottom_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_cement_event_id'), 'ops_plan_cement', ['event_id'], unique=False)
    op.create_table('ops_plan_costs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_costs_event_id'), 'ops_plan_costs', ['event_id'], unique=False)
    op.create_table('ops_plan_directional',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('inclination', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('azimuth', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('tvd', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('ns', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('ew', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('dls', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_directional_event_id'), 'ops_plan_directional', ['event_id'], unique=False)
    op.create_table('ops_plan_formation_tops',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=300), nullable=True),
    sa.Column('md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('tvd', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('lithology', sa.String(length=300), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_formation_tops_event_id'), 'ops_plan_formation_tops', ['event_id'], unique=False)
    op.create_table('ops_plan_hole',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=True),
    sa.Column('hole_size_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bit_type', sa.String(length=300), nullable=True),
    sa.Column('top_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bottom_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('length_ft', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_hole_event_id'), 'ops_plan_hole', ['event_id'], unique=False)
    op.create_table('ops_plan_mud',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=True),
    sa.Column('mud_type', sa.String(length=300), nullable=True),
    sa.Column('top_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('bottom_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('weight_min', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('weight_max', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_mud_event_id'), 'ops_plan_mud', ['event_id'], unique=False)
    op.create_table('ops_plan_risks',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=60), nullable=True),
    sa.Column('likelihood', sa.String(length=60), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_risks_event_id'), 'ops_plan_risks', ['event_id'], unique=False)
    op.create_table('ops_plan_time_depth',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('planned_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('phase', sa.String(length=300), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_time_depth_event_id'), 'ops_plan_time_depth', ['event_id'], unique=False)
    op.add_column('ops_well_plans', sa.Column('objective_primary', sa.Text(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('objective_secondary', sa.Text(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('target_formation', sa.String(length=200), nullable=True))
    op.add_column('ops_well_plans', sa.Column('geology_prognosis', sa.Text(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('kop_md', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('max_inclination', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('target_azimuth', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('rig_name', sa.String(length=200), nullable=True))
    op.add_column('ops_well_plans', sa.Column('rig_type', sa.String(length=100), nullable=True))
    op.add_column('ops_well_plans', sa.Column('planned_spud_date', sa.Date(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('surface_location', sa.String(length=300), nullable=True))
    op.add_column('ops_well_plans', sa.Column('surface_northing', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('surface_easting', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('ops_well_plans', sa.Column('dry_hole_cost', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('completion_cost', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('contingency_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.alter_column('ops_well_plans', 'budget_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
    # Legacy processed_datasets/processed_records/wells churn pruned (runtime-
    # reflected tables, not ORM-owned) — same as every prior ops migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned to match upgrade)
    op.alter_column('ops_well_plans', 'budget_total',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.drop_column('ops_well_plans', 'contingency_pct')
    op.drop_column('ops_well_plans', 'completion_cost')
    op.drop_column('ops_well_plans', 'dry_hole_cost')
    op.drop_column('ops_well_plans', 'currency')
    op.drop_column('ops_well_plans', 'surface_easting')
    op.drop_column('ops_well_plans', 'surface_northing')
    op.drop_column('ops_well_plans', 'surface_location')
    op.drop_column('ops_well_plans', 'planned_spud_date')
    op.drop_column('ops_well_plans', 'rig_type')
    op.drop_column('ops_well_plans', 'rig_name')
    op.drop_column('ops_well_plans', 'target_azimuth')
    op.drop_column('ops_well_plans', 'max_inclination')
    op.drop_column('ops_well_plans', 'kop_md')
    op.drop_column('ops_well_plans', 'geology_prognosis')
    op.drop_column('ops_well_plans', 'target_formation')
    op.drop_column('ops_well_plans', 'objective_secondary')
    op.drop_column('ops_well_plans', 'objective_primary')
    op.drop_index(op.f('ix_ops_plan_time_depth_event_id'), table_name='ops_plan_time_depth')
    op.drop_table('ops_plan_time_depth')
    op.drop_index(op.f('ix_ops_plan_risks_event_id'), table_name='ops_plan_risks')
    op.drop_table('ops_plan_risks')
    op.drop_index(op.f('ix_ops_plan_mud_event_id'), table_name='ops_plan_mud')
    op.drop_table('ops_plan_mud')
    op.drop_index(op.f('ix_ops_plan_hole_event_id'), table_name='ops_plan_hole')
    op.drop_table('ops_plan_hole')
    op.drop_index(op.f('ix_ops_plan_formation_tops_event_id'), table_name='ops_plan_formation_tops')
    op.drop_table('ops_plan_formation_tops')
    op.drop_index(op.f('ix_ops_plan_directional_event_id'), table_name='ops_plan_directional')
    op.drop_table('ops_plan_directional')
    op.drop_index(op.f('ix_ops_plan_costs_event_id'), table_name='ops_plan_costs')
    op.drop_table('ops_plan_costs')
    op.drop_index(op.f('ix_ops_plan_cement_event_id'), table_name='ops_plan_cement')
    op.drop_table('ops_plan_cement')
    op.drop_index(op.f('ix_ops_plan_casing_event_id'), table_name='ops_plan_casing')
    op.drop_table('ops_plan_casing')
    # ### end Alembic commands ###
