"""well plan afe extra fields

Revision ID: e6bcd407a81a
Revises: 66ad1204ad96
Create Date: 2026-07-23 23:05:51.003314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6bcd407a81a'
down_revision: Union[str, None] = '66ad1204ad96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ops_well_plans', sa.Column('approved_by', sa.String(length=200), nullable=True))
    op.add_column('ops_well_plans', sa.Column('engineer', sa.String(length=200), nullable=True))
    op.add_column('ops_well_plans', sa.Column('est_days', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('authorized_md', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ops_well_plans', sa.Column('authorized_tvd', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ops_well_plans', 'authorized_tvd')
    op.drop_column('ops_well_plans', 'authorized_md')
    op.drop_column('ops_well_plans', 'est_days')
    op.drop_column('ops_well_plans', 'engineer')
    op.drop_column('ops_well_plans', 'approved_by')
    # ### end Alembic commands ###
