"""ops registers + casing running tables

Revision ID: f3dc2669d180
Revises: f72e908f3d10
Create Date: 2026-07-24 17:19:01.160973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3dc2669d180'
down_revision: Union[str, None] = 'f72e908f3d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_reg_bop_tests',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('test_type', sa.String(length=60), nullable=True),
    sa.Column('component', sa.String(length=60), nullable=True),
    sa.Column('low_psi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('high_psi', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('hold_min', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('result', sa.String(length=60), nullable=True),
    sa.Column('next_due', sa.String(length=300), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reg_bop_tests_event_id'), 'ops_reg_bop_tests', ['event_id'], unique=False)
    op.create_table('ops_reg_certifications',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=300), nullable=True),
    sa.Column('cert_type', sa.String(length=60), nullable=True),
    sa.Column('holder', sa.String(length=300), nullable=True),
    sa.Column('authority', sa.String(length=300), nullable=True),
    sa.Column('issued', sa.String(length=300), nullable=True),
    sa.Column('expires', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reg_certifications_event_id'), 'ops_reg_certifications', ['event_id'], unique=False)
    op.create_table('ops_reg_hse_incidents',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('severity', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reg_hse_incidents_event_id'), 'ops_reg_hse_incidents', ['event_id'], unique=False)
    op.create_table('ops_reg_lessons',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('phase', sa.String(length=300), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('npt_hours', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('impact', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reg_lessons_event_id'), 'ops_reg_lessons', ['event_id'], unique=False)
    op.create_table('ops_reg_materials',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('item', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('planned_qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('consumed_qty', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('on_hand', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reg_materials_event_id'), 'ops_reg_materials', ['event_id'], unique=False)
    op.create_table('ops_casing_running',
    sa.Column('daily_report_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('string', sa.String(length=60), nullable=True),
    sa.Column('od_in', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('planned_shoe_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('actual_shoe_md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('joints_run', sa.Integer(), nullable=True),
    sa.Column('running_hours', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('mud_displaced_bbl', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('returns_pct', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('landed', sa.String(length=60), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['ops_daily_reports.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_casing_running_daily_report_id'), 'ops_casing_running', ['daily_report_id'], unique=False)
    # Legacy processed_datasets/processed_records/wells churn pruned as usual.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned)
    op.drop_index(op.f('ix_ops_casing_running_daily_report_id'), table_name='ops_casing_running')
    op.drop_table('ops_casing_running')
    op.drop_index(op.f('ix_ops_reg_materials_event_id'), table_name='ops_reg_materials')
    op.drop_table('ops_reg_materials')
    op.drop_index(op.f('ix_ops_reg_lessons_event_id'), table_name='ops_reg_lessons')
    op.drop_table('ops_reg_lessons')
    op.drop_index(op.f('ix_ops_reg_hse_incidents_event_id'), table_name='ops_reg_hse_incidents')
    op.drop_table('ops_reg_hse_incidents')
    op.drop_index(op.f('ix_ops_reg_certifications_event_id'), table_name='ops_reg_certifications')
    op.drop_table('ops_reg_certifications')
    op.drop_index(op.f('ix_ops_reg_bop_tests_event_id'), table_name='ops_reg_bop_tests')
    op.drop_table('ops_reg_bop_tests')
    # ### end Alembic commands ###
