"""geopressure grid, design scenarios, plan approval

Revision ID: f72e908f3d10
Revises: 77ce554bed28
Create Date: 2026-07-24 16:06:53.828921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f72e908f3d10'
down_revision: Union[str, None] = '77ce554bed28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_plan_geopressure',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('md', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('tvd', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('pore_ppg', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('frac_ppg', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('temp_f', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['ops_events.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_plan_geopressure_event_id'), 'ops_plan_geopressure', ['event_id'], unique=False)
    op.add_column('ops_engineering_designs', sa.Column('scenario', sa.String(length=60), server_default='Base', nullable=False))
    op.drop_constraint('uq_eng_design_event_module', 'ops_engineering_designs', type_='unique')
    op.create_unique_constraint('uq_eng_design_event_module_scenario', 'ops_engineering_designs', ['event_id', 'module', 'scenario'])
    op.add_column('ops_well_plans', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ops_well_plans', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('ops_well_plans', sa.Column('approved_by_user', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_ops_well_plans_submitted_by', 'ops_well_plans', 'users', ['submitted_by'], ['id'])
    op.create_foreign_key('fk_ops_well_plans_approved_by_user', 'ops_well_plans', 'users', ['approved_by_user'], ['id'])
    # Legacy processed_datasets/processed_records/wells churn pruned as usual.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (legacy processed_datasets/processed_records/wells churn pruned)
    op.drop_constraint('fk_ops_well_plans_approved_by_user', 'ops_well_plans', type_='foreignkey')
    op.drop_constraint('fk_ops_well_plans_submitted_by', 'ops_well_plans', type_='foreignkey')
    op.drop_column('ops_well_plans', 'approved_by_user')
    op.drop_column('ops_well_plans', 'approved_at')
    op.drop_column('ops_well_plans', 'submitted_by')
    op.drop_column('ops_well_plans', 'submitted_at')
    op.drop_column('ops_well_plans', 'is_locked')
    op.drop_constraint('uq_eng_design_event_module_scenario', 'ops_engineering_designs', type_='unique')
    op.create_unique_constraint('uq_eng_design_event_module', 'ops_engineering_designs', ['event_id', 'module'])
    op.drop_column('ops_engineering_designs', 'scenario')
    op.drop_index(op.f('ix_ops_plan_geopressure_event_id'), table_name='ops_plan_geopressure')
    op.drop_table('ops_plan_geopressure')
    # ### end Alembic commands ###
